name: 'deploy-accounts'

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  accounts-deploy:
    name: 'deploy-accounts'
    runs-on: ubuntu-latest
    environment: accounts

    defaults:
      run:
        shell: bash

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::104782207494:role/GithubActionsRole
          aws-region: us-east-1

      - name: Terraform Format
        run: terraform -chdir=accounts fmt -check

      - name: Terraform Init
        run: terraform -chdir=accounts init

      - name: Terraform Validate
        run: terraform -chdir=accounts validate -check

      - name: Terraform Plan
        run: terraform -chdir=accounts plan -input=false

      - name: Terraform Apply
        run: terraform -chdir=accounts apply -auto-approve -input=false
