name: 'deploy-staging'

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  staging-deploy:
    name: 'deploy-staging'
    runs-on: ubuntu-latest
    environment: staging

    defaults:
      run:
        shell: bash
        working-directory: stage

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_MANAGEMENT_ROLE }}
          aws-region: us-east-1

      - name: Setup Terraform variables
        run: |-
          cat <<EOT >> terraform.tfvars

          role_arn = ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}
          EOT

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
